# typed: false
# frozen_string_literal: true

# This formula is auto-generated by scripts/update-homebrew.sh — do not edit manually.
class Tigris < Formula
  desc "Command line interface for Tigris object storage"
  homepage "https://www.tigrisdata.com"
  license "MIT"
  version "2.14.0-beta.6"

  on_macos do
    on_arm do
      url "https://github.com/tigrisdata/cli/releases/download/v2.14.0-beta.6/tigris-darwin-arm64.tar.gz"
      sha256 "a660bf3fff04afe738b24bbe43b2c0b1faa3792d55100658c2ff7482c45529f6"
    end
    on_intel do
      url "https://github.com/tigrisdata/cli/releases/download/v2.14.0-beta.6/tigris-darwin-x64.tar.gz"
      sha256 "386daa6e8b931a047d036fc6ea640471bb9dcda464affcecfc1e774ffb5d38a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tigrisdata/cli/releases/download/v2.14.0-beta.6/tigris-linux-arm64.tar.gz"
      sha256 "0a0de0a6bda20717179e92afbab23f24daec3e8a1cae5e550eb7574c3284d6fe"
    end
    on_intel do
      url "https://github.com/tigrisdata/cli/releases/download/v2.14.0-beta.6/tigris-linux-x64.tar.gz"
      sha256 "a06793a93ed1c06f499cdc526a70bdaa5305bb9fc54a472f48d9d50cfec72256"
    end
  end

  def install
    host_os = OS.mac? ? "darwin" : "linux"
    host_arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "tigris-#{host_os}-#{host_arch}" => "tigris"
    bin.install_symlink "tigris" => "t3"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tigris --version")
  end
end
