# typed: false
# frozen_string_literal: true

# This formula is auto-generated by scripts/update-homebrew.sh — do not edit manually.
# The url fields are filled with GitHub's own asset download URLs (copied
# verbatim from the release API), because the CLI's release tag
# (@tigrisdata/cli@<version>) contains '/' and '@' and is not safe to
# hand-assemble into a path.
class Tigris < Formula
  desc "Command line interface for Tigris object storage"
  homepage "https://www.tigrisdata.com"
  license "MIT"
  version "3.12.1"

  on_macos do
    on_arm do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.12.1/tigris-darwin-arm64.tar.gz"
      sha256 "32be1c7bea8cf85ef9ecd190e95582c0cfae79faa5eb2b4738aa08e323b8dea4"
    end
    on_intel do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.12.1/tigris-darwin-x64.tar.gz"
      sha256 "38277107b3662257e1f44ee8c018209d658b1a5346397af0aa901f749f3d14d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.12.1/tigris-linux-arm64.tar.gz"
      sha256 "fa1b7b81a98131cefda7c56ff45ac0773f5129934cb04064400e5a1a40188ec6"
    end
    on_intel do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.12.1/tigris-linux-x64.tar.gz"
      sha256 "7f1109624f0da41d01b56d7e8590cc54af38fa249252cea9f152a869c53b8e81"
    end
  end

  def install
    host_os = OS.mac? ? "darwin" : "linux"
    host_arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "tigris-#{host_os}-#{host_arch}" => "tigris"
    bin.install_symlink "tigris" => "t3"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tigris --version")
  end
end
