# typed: false
# frozen_string_literal: true

# This formula is auto-generated by scripts/update-homebrew.sh — do not edit manually.
# The url fields are filled with GitHub's own asset download URLs (copied
# verbatim from the release API), because the CLI's release tag
# (@tigrisdata/cli@<version>) contains '/' and '@' and is not safe to
# hand-assemble into a path.
class Tigris < Formula
  desc "Command line interface for Tigris object storage"
  homepage "https://www.tigrisdata.com"
  license "MIT"
  version "3.9.0"

  on_macos do
    on_arm do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.9.0/tigris-darwin-arm64.tar.gz"
      sha256 "c355558bfbff29aa8f0ff31452b42f9099fd2c37757afc30d2a539c1356ecb67"
    end
    on_intel do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.9.0/tigris-darwin-x64.tar.gz"
      sha256 "50d7e6ed17c667c99f0b8796eca0363603a038142072cec026f75fe24deb9fa2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.9.0/tigris-linux-arm64.tar.gz"
      sha256 "4d7b74e8d0aa7ef119f58dba7df597d9d2391ebc43a58a210d7851115c82c06e"
    end
    on_intel do
      url "https://github.com/tigrisdata/storage/releases/download/%40tigrisdata/cli%403.9.0/tigris-linux-x64.tar.gz"
      sha256 "9af289ced5fa8f5c803ecf87fe1233fd5b2961433e5e48ea24d77c4eab556efa"
    end
  end

  def install
    host_os = OS.mac? ? "darwin" : "linux"
    host_arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "tigris-#{host_os}-#{host_arch}" => "tigris"
    bin.install_symlink "tigris" => "t3"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tigris --version")
  end
end
